#!/bin/bash
if [ -z "$1" ]
then
	echo "PLEASE PROVIDE THE WEBSITE URL"
	exit 1
fi
cd /tmp/
 wget --mirror --convert-links --html-extension --wait=2  -o log $1
#wget -mkEpnp  $1
#wget --mirror --convert-links --adjust-extension --page-requisites  --no-parent  $1
#--mirror – Makes (among other things) the download recursive.
#--convert-links – convert all the links (also to stuff like CSS stylesheets) to relative, so it will be suitable for offline viewing.
#--adjust-extension – Adds suitable extensions to filenames (html or css) depending on their content-type.
#--page-requisites – Download things like CSS style-sheets and images required to properly display the page offline.
#--no-parent – When recursing do not ascend to the parent directory. It useful for restricting the download to only a portion of the site.

echo -e "\n\n=======>>>>>   WEBSITE IS DOWNLOADED AT /tmp/ <<<<<============="
