#!/bin/bash
#Author : GOPESH CHAUDHARY
#Description : Jenkins Pull Request Generator
#Date : 12 April 2018
#ID : BBPR  ( BitBucket Pull Requester )
#INPUTS : $BBPR_EMAIL  $BBPR_PASS  

#GENERATING BRANCH INCREMENTER
if [ -z "$BBPR_EMAIL" ]
then
      echo "'BBPR_EMAIL' is not set in parametrized string - bitbucket login -> email"
#      exit 1;
fi
if [ -z "$BBPR_PASS" ]
then
      echo "'BBPR_PASS' is not set in parametrized string - bitbucket login -> password"
#      exit 1;
fi
if [ -z "$BBPR_ID" ]
then
      echo "'BBPR_ID' is not set in parametrized string - bitbucket userid"
#      exit 1;
fi
if [ -z "$BBPR_REPO" ]
then
      echo "'BBPR_REPO' is not set in parametrized string - bitbucket reponame"
#      exit 1;
fi
BBPR_EMAIL="kushankjain12@gmail.com"
BBPR_PASS="coolguy555"
BBPR_ID="kjain12"
BBPR_REPO="test_android"
CURRBRANCH="release/1.1"   #${GIT_BRANCH#*/} 
BUILD_NUMBER=6
BRANCH_FILE="branchlists"
BITBUCKET_BRANCHS="https://api.bitbucket.org/2.0/repositories/$BBPR_ID/$BBPR_REPO/refs/branches"
BITBUCKET_PULLREQUEST="https://api.bitbucket.org/2.0/repositories/$BBPR_ID/$BBPR_REPO/pullrequests"
##############################--PATCHING --- ############################################
$(curl -sS -H "Content-Type: application/json" -u $BBPR_EMAIL:$BBPR_PASS  $BITBUCKET_BRANCHS > $BRANCH_FILE)
SIZE=$(grep -Po '"size": \d+' $BRANCH_FILE | sed 's/"size": \(\)/\1/g')
PAGELEN=$(grep -Po '"pagelen": \d+' $BRANCH_FILE | sed 's/"pagelen": \(\)/\1/g')
echo "Total is $SIZE"
echo "Max Per Page is $PAGELEN"
LOOPER=$(echo `/usr/bin/perl -w -e "use POSIX; print ceil($SIZE/$PAGELEN), qq{\n}"`)
if [ -z "$LOOPER" ] || [ $LOOPER -eq 0 ];
then
      echo "NO BRANCH RESULT FOUND IN [ $BBPR_REPO ] REPOSITORY.SIZE= $SIZE PAGELEN = $PAGELEN"
      exit 1;
fi
echo "LOOPING UPTO $LOOPER"
$(truncate -s 0 $BRANCH_FILE)
for ((i=1; i<=$LOOPER; i++))
do
   echo $i
   echo $BITBUCKET_BRANCHS"?page=$i"
   $(curl -sS -H "Content-Type: application/json" -u $BBPR_EMAIL:$BBPR_PASS  $BITBUCKET_BRANCHS"?page=$i" |grep -P '"type": "branch", "name": "release[\w\/.\-]+",' -o | sed 's/"type": "branch", "name": "\([[:alpha:][:digit:]\/\.\-]\+\)",/\1/g' >>  $BRANCH_FILE)
done
#$(curl -sS -H "Content-Type: application/json" -u $BBPR_EMAIL:$BBPR_PASS  $BITBUCKET_BRANCHS |grep -P '"type": "branch", "name": "release[\w\/.]+",' -o | sed 's/"type": "branch", "name": "\([[:alpha:][:digit:]\/\.]\+\)",/\1/g' >>  $BRANCH_FILE)
if grep -qF "$CURRBRANCH" $BRANCH_FILE;then
   echo "SUCCESSFULLY VALIDATED BRANCH [ $CURRBRANCH ]"
else
   echo "NO SUCH BRANCH FOUND IN REPOSITORY [ $CURRBRANCH ]"
   exit 1;
fi
ESCCURRBRANCH=$(echo "$CURRBRANCH" | sed 's/\//\\\//g')
NEXTBRANCH=$(sed -n '/'$ESCCURRBRANCH'/{n;p;}' $BRANCH_FILE)
if [ -z "$NEXTBRANCH" ]
then
      echo "NO ADVANCE BRANCH FOUND FOR [ $CURRBRANCH ], NO PULL REQUEST CAN BE GENERATED."
      exit 1;
else
      echo "TRYING TO CREATE PULL REQUEST : [ $CURRBRANCH ] --> [ $NEXTBRANCH ]"
fi
exit;
PULLOUT=`curl -sS -X POST -H "Content-Type: application/json" -u $BBPR_EMAIL:$BBPR_PASS -d '{"destination":{"branch":{"name":"'$NEXTBRANCH'"}},"source":{"branch":{"name":"'$CURRBRANCH'"}},"title":"JENKINS-PR '$BUILD_NUMBER'","description": "This is an automated pull request generated by Jenkins."}' $BITBUCKET_PULLREQUEST`
if [[ $PULLOUT = *"pullrequest"* ]]; then
  echo "PULL REQUEST SUBMITTED SUCCESSFULLY!!"
else
  echo "PULL REQUEST ATTEMPT FAILED. KINDLY CHECK NETWORK/BITBUCKET CONNECTIVITY."
fi
