#!/bin/bash
wget http://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2 -O ./GnuParallel.tar.bz2
rm -rf GnuParallel.tar
bunzip2 GnuParallel.tar.bz2
tar xvf ./GnuParallel.tar -C ./
echo "Now Move inside folder and try to make it."
echo "./configure && make && sudo make install"
